config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :rides do
    resources :ride_requests # table name aayaga yaha pe
  end
  resources :users
  resources :ride_requests
  resources :logins, only: [:create, :new]
  resource :logout, only: [:destroy]
  resource :welcome, only: [:index]

  root 'welcome#index'

end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cab.rb
# frozen_string_literal: true

class Cab < ApplicationRecord
  has_many :rides

  validates :cab_number, :number_of_seats, presence: true
  validates :cab_number, length: { in: 10..10 }
  validates :number_of_seats, numericality: { only_integer: true }
end

app/models/driver.rb
# frozen_string_literal: true


class Driver < ApplicationRecord
  
  has_many :ride
  validates :first_name, :last_name, :contact_number, :email, :password, presence: true
  validates :contact_number, uniqueness: true
  validates :contact_number, length: { in: 10..10 }
  validates :contact_number, numericality: { only_integer: true }
  validates :licence_number, length: { in: 15..15 }
  before_save do
    self.first_name = first_name.titleize
    self.last_name = last_name.titleize
  end
end

app/models/ride.rb
# frozen_string_literal: true

class Ride < ApplicationRecord
  belongs_to :driver
  belongs_to :cab
  has_many :ride_requests
  #validates :date, :time, :location, :cab_id, :driver_id, presence: true
  def driver_name
    driver.first_name + ' ' + driver.last_name
  end
end

app/models/ride_request.rb
# frozen_string_literal: true

class RideRequest < ApplicationRecord
  belongs_to :user
  belongs_to :ride
  validates :status, :destination, presence: true
  #validates :user_id ,uniqueness: true
end

app/models/user.rb
# frozen_string_literal: true
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~  /\A[a-zA-Z0-9]+[.,_]*[a-zA-Z0-9]*[@][a-zA-Z0-9]+[.][a-zA-Z0-9]+\Z/i
      record.errors[attribute] << (options[:message] || "is not an email")
    end
  end
end
class User < ApplicationRecord
  has_many :ride_request
  validates :first_name, :last_name, :contact_number, :email, :password, presence: true
  validates :contact_number, uniqueness: true
  validates :email, confirmation: true
  validates :contact_number, length: { in: 10..10 }
  validates :contact_number, numericality: { only_integer: true }
  validates :email, email: true
  validates :password, length: { in: 6..20 }
  has_secure_password
  before_save do
    self.first_name = first_name.titleize
    self.last_name = last_name.titleize
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :logged_in?
  before_action :authorized
  def current_user   
    User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end

  def authorized
    redirect_to root_path() unless logged_in?
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]
  def new
  end
  def create
    @user=User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path(), notice: "Hii #{@user.first_name} #{@user.last_name}"
    else
      redirect_to new_login_path(), alert: "Wrong Credentials"
    end
  end
end

app/controllers/logouts_controller.rb
class LogoutsController < ApplicationController
  def destroy
    session[:user_id] = nil
    redirect_to root_path()
  end
end

app/controllers/ride_requests_controller.rb
# frozen_string_literal: true

class RideRequestsController < ApplicationController
  @@rideid = ""
  def index
    id = params['ride_id']
    @requests = RideRequest.where(ride_id: id)
  end
  def new 
    #params
    @@rideid = params["ride_id"]

  end
  def create
    puts "dsadasdas", params
    obj = User.find_by(email: params["email"])
    RideRequest.create(destination: params["Destination"], status: "booked", user_id: obj.id, ride_id: @@rideid)
    redirect_to rides_path
  end

end

app/controllers/rides_controller.rb
# frozen_string_literal: true

class RidesController < ApplicationController
  def index
    rides = []
    driver_name = []
    Ride.all.each do |ele|
      rides.push(ele)
      ride_count = Ride.count
    end
    @all = rides
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    puts params
  end

  def new

  end
  def create
    puts params
    User.create(first_name: params["first_name"],last_name: params["last_name"],contact_number: params["contact_number"],email: params["email"],password: params["password"])
    redirect_to rides_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    skip_before_action :authorized, only: [:index]

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/logouts_helper.rb
module LogoutsHelper
end

app/helpers/ride_requests_helper.rb
# frozen_string_literal: true

module RideRequestsHelper
end

app/helpers/rides_helper.rb
# frozen_string_literal: true

module RidesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myfirstrailsapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/logins/new.html.erb
<p><%= alert %> </p>

<%= form_with(url: "/logins", method: "POST") do %>
  
  <%= label_tag(:email, "email_id") %>
  <%= text_field_tag(:email) %>
  <br/>
  <%= label_tag(:password, "password") %>
  <%= password_field_tag(:password) %>
  <br/>
  <%= submit_tag("Submit") %>
<% end %>

app/views/ride_requests/index.html.erb
<html>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<head> <h1>List of Rides</h1> </head>
<title>Ride list </title>
<body>
  <table style="width:50%">
  <tr>
    <th>User Name</th>
    <th>Status</th>
    
  </tr>
  <% @requests.each do |ele| %>
  <tr>
    <td><%=ele.user.first_name%></td>
    <td><%=ele.status%></td>
   

  </tr>
  <% end%>
</table>

  

</body>
</html>

app/views/ride_requests/new.haml
= form_with(url: "/ride_requests", method: "POST") do
 
  %br
  = label_tag(:destination, " Destination")
  = text_field_tag(:Destination)
  %br
  = label_tag(:email, "email_id")
  = text_field_tag(:email)
  %br
  = label_tag(:password, "password")
  = password_field_tag(:password)
  %br
  = submit_tag("Submit")

  / = @@rideid

app/views/rides/index.html.erb
<html>

<head> 
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <h1 style="text-align: center; font-weight: bolder;font-family: sans-serif;">List of Rides</h1> </head>
<title>Ride list </title>
<body>
  <table class="table">
  <tr>
    <th>Driver_Id</th>
    <th>Date</th>
    <th>Time</th>
    <th>Location</th>
    <th>Driver Name</th>
    <th>Request Count</th>
    <th>Book Rides</th>
    <th>View Request</th>
  </tr>
  <% @all.each do |ele| %>
  <tr>
    <td><%=ele.id%></td>
    <td><%=ele.date%></td>
    <td><%=ele.time.strftime("%T:%M%p") %></td>
    <td><%=ele.location%></td>
    <td><%=ele.driver_name%></td>
    <td><%=ele.ride_requests.count%></td>
    <td><%=link_to 'Book Ride', new_ride_ride_request_path(ele) %></td>
    <td><%=link_to 'View Requests', ride_ride_requests_path(ele) %></td>

  </tr>
  <% end%>
</table>
 <a href="/users/new"  type="button" class="btn btn-default">create new user</a>
 <!-- <a href="/ride_requests/new"  type="button" class="btn btn-default">book ride</a> -->
  
<div><p><%=@error%></p></div>
</body>
</html>

app/views/users/new.haml
= form_with(url: "/users", method: "POST") do
  = label_tag(:first_name, "First Name")
  = text_field_tag(:first_name)
  %br
  = label_tag(:last_name, "Last Name")
  = text_field_tag(:last_name)
  %br
  = label_tag(:contact_number, "Contact Number")
  = text_field_tag(:contact_number)
  %br
  = label_tag(:email, "email_id")
  = text_field_tag(:email)
  %br
  = label_tag(:password, "password")
  = password_field_tag(:password)
  %br
  = submit_tag("Submit")
%p
  =@error

app/views/welcome/index.html.erb
<h1>Welcome</h1>

<% if logged_in? %>   
  <p><%= notice %> </p>

  <h1>You are Logged In, <%= current_user.email %></h1>
  <%= button_to "Rides", '/rides', method: :get%>
  <%= button_to "Logout", logout_path, method: :delete %>
 
<% else %>
  <%= button_to "Sign Up", '/users/new', method: :get%>
  <%= button_to "Login", new_login_path(), method: :get%>
<%end%>